# Generated by Django 3.2.7 on 2021-09-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='body_text',
            new_name='text',
        ),
    ]
