# Generated by Django 3.2.6 on 2021-09-30 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_artical'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
