# Generated by Django 3.2.6 on 2021-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_artical_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
