# Generated by Django 3.2.6 on 2021-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_artical_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
