# Generated by Django 3.2.6 on 2021-10-11 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_artical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='author_detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headline',
            name='image_detail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='text_detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headline',
            name='time_detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headline',
            name='title_detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
